# nginx-active-service
apiVersion: v1
kind: Service
metadata:
  name: blue-green-canary-active
spec:
  selector:
    app: blue-green-canary
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

# nginx-active-preview
apiVersion: v1
kind: Service
metadata:
  name: blue-green-canary-preview
spec:
  selector:
    app: blue-green-canary
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080